server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: qwerty123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    token:
      expiration: 70000
      sign: niuamncuimcniuamnuinUIANCIUASNCuacnauiscmqiq
    refresh-token:
      expiration: 86400000
      sign: niuamncuasdasdasdadasczcbryacnauiscmqiq
