server:
  port: 8090
  forward-headers-strategy: native

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: catalogue-service-route
          uri: lb://catalogue-service
          predicates:
            - Host=catalogue.api.192.168.0.104.nip.io
        - id: manager
          uri: lb://manager
          predicates:
            - Host=manager.app.192.168.0.104.nip.io

eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
    prefer-id-address: true