server:
  port: 8888
spring:
  profiles:
    active: native
  security:
    user: 
      name: config
      password: config-password
      roles:
        - CONFIG
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/Java/delivery/config/cloud/{application}/{profile}
          